# Generated by Django 3.1.3 on 2021-01-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testNum', models.CharField(max_length=200)),
                ('numOfAttemptedLogins', models.IntegerField()),
                ('numOfDeniedLogins', models.IntegerField()),
                ('numOfAcceptedLogins', models.IntegerField()),
                ('percentsWhenDenied', models.JSONField()),
                ('percentsWhenAccepted', models.JSONField()),
                ('numOfDeniedLoginsCorrect', models.IntegerField()),
                ('numOfAcceptedLoginsIncorrect', models.IntegerField()),
                ('dwelldataForKeyE', models.JSONField()),
                ('dwelldataForKeyA', models.JSONField()),
                ('dwelldataForKeyR', models.JSONField()),
                ('dwelldataForKeyI', models.JSONField()),
                ('dwelldataForKeyO', models.JSONField()),
                ('flightdataForKeysTH', models.JSONField()),
                ('flightdataForKeysHE', models.JSONField()),
                ('flightdataForKeysAN', models.JSONField()),
                ('flightdataForKeysIN', models.JSONField()),
                ('flightdataForKeysER', models.JSONField()),
                ('numOfAcceptedLoginsCorrect', models.IntegerField()),
                ('numOfDeniedLoginsIncorrect', models.IntegerField()),
            ],
        ),
    ]
