# Generated by Django 3.1.3 on 2021-01-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20210103_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='dwelldataForKeyA',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='stat',
            name='dwelldataForKeyE',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='stat',
            name='dwelldataForKeyI',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='stat',
            name='dwelldataForKeyO',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='stat',
            name='dwelldataForKeyR',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='stat',
            name='flightdataForKeysAN',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='stat',
            name='flightdataForKeysER',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='stat',
            name='flightdataForKeysHE',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='stat',
            name='flightdataForKeysIN',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='stat',
            name='flightdataForKeysTH',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='stat',
            name='numOfAcceptedLogins',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='stat',
            name='numOfAcceptedLoginsCorrect',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='stat',
            name='numOfAcceptedLoginsIncorrect',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='stat',
            name='numOfAttemptedLogins',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='stat',
            name='numOfDeniedLogins',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='stat',
            name='numOfDeniedLoginsCorrect',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='stat',
            name='numOfDeniedLoginsIncorrect',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='stat',
            name='percentsWhenAccepted',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='stat',
            name='percentsWhenDenied',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='stat',
            name='testNum',
            field=models.CharField(max_length=200),
        ),
    ]
