# Generated by Django 3.1.3 on 2021-01-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20210103_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='percentsWhenAcceptedCorrect',
            field=models.JSONField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='stat',
            name='percentsWhenAcceptedIncorrect',
            field=models.JSONField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='stat',
            name='percentsWhenDeniedCorrect',
            field=models.JSONField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='stat',
            name='percentsWhenDeniedIncorrect',
            field=models.JSONField(blank=True, default='[]'),
        ),
    ]
