# Generated by Django 3.1.3 on 2021-01-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_auto_20210103_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='usernamesWhenAccepted',
            field=models.JSONField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='stat',
            name='usernamesWhenAcceptedCorrect',
            field=models.JSONField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='stat',
            name='usernamesWhenAcceptedIncorrect',
            field=models.JSONField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='stat',
            name='usernamesWhenDenied',
            field=models.JSONField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='stat',
            name='usernamesWhenDeniedCorrect',
            field=models.JSONField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='stat',
            name='usernamesWhenDeniedIncorrect',
            field=models.JSONField(blank=True, default='[]'),
        ),
    ]
