# Generated by Django 3.1.3 on 2021-01-04 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_auto_20210103_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='usernamesWhenAccepted',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='usernamesWhenAcceptedCorrect',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='usernamesWhenAcceptedIncorrect',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='usernamesWhenDenied',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='usernamesWhenDeniedCorrect',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='usernamesWhenDeniedIncorrect',
        ),
    ]
